(define (problem task)
(:domain office_domain)
(:objects
    main_door kitchen_shelf microwave kitchen_sink kitchen_counter entrance main_office_desk main_office_cabinet main_entrance coffee_table_1 coffee_table_2 main_office_cupboard kitchen_table_1 kitchen_table_5 main_office_corridor kitchen_corridor kitchen_chair meeting_room main_office_entrance main_office_doorway kitchen_corridor_2 kitchen_hallway meeting_room_door main_office_door coffee_table_3 coffee_table_4 kitchen_table_2 corridor_centre meeting_room_hallway corridor kitchen_table_4 fridge corridor_shelf_2 kitchen_table_3 corridor_shelf_1 kitchen_door_2 kitchen_door_1 office_door_1 office_entrance_1 office_desk_2_storage office_desk_3_storage office_entrance_2 office_door_2 office_desk_1_storage office_desk_5_storage office_desk_2_cabinet office_desk_3 office_desk_2 office_desk_1 office_corridor office_desk_5 office_shelf_2 office_shelf_3 office_storage_2 office_shelf_1 office_storage_1 office_desk_4_storage office_desk_1_cabinet - waypoint
    robot_assistant - robot
    paper mug post1 post2 - object 
    person1 person2 person3 - person
)
(:init
    (robot_at robot_assistant kitchen_sink)
    (not_moving robot_assistant)
    (object_at paper kitchen_shelf)
    (object_at mug microwave)
    (object_at post1 office_entrance_1)
    (object_at post2 office_entrance_1)
    (graspable paper)
    (graspable mug)
    (graspable post1)
    (graspable post2)
    (not_holding_object robot_assistant)
    (person_not_found  person1)  
    (person_not_found  person2)
    (person_nexto person2 kitchen_corridor) 
    (not_occupied main_door)
    (not_occupied kitchen_shelf)
    (not_occupied microwave)
    (not_occupied microwave)
    (not_occupied kitchen_counter)
    (not_occupied entrance)
    (not_occupied main_office_desk)
    (not_occupied main_office_cabinet)
    (not_occupied main_entrance)
    (not_occupied coffee_table_1)
    (not_occupied coffee_table_2)
    (not_occupied main_office_cupboard)
    (not_occupied kitchen_table_1)
    (not_occupied kitchen_table_1)
    (not_occupied main_office_corridor)
    (not_occupied kitchen_corridor)
    (not_occupied kitchen_chair)
    (not_occupied meeting_room)
    (not_occupied main_office_entrance)
    (not_occupied main_office_doorway)
    (not_occupied kitchen_corridor_2)
    (not_occupied kitchen_hallway)
    (not_occupied meeting_room_door)
    (not_occupied meeting_room_door)
    (not_occupied coffee_table_3)
    (not_occupied coffee_table_4)
    (not_occupied kitchen_table_2)
    (not_occupied corridor_centre)
    (not_occupied meeting_room_hallway)
    (not_occupied corridor)
    (not_occupied kitchen_table_4)
    (not_occupied fridge)
    (not_occupied corridor_shelf_2)
    (not_occupied corridor_shelf_2)
    (not_occupied corridor_shelf_1)
    (not_occupied kitchen_door_2)
    (not_occupied kitchen_door_1)
    (not_occupied office_door_1)
    (not_occupied office_entrance_1)
    (not_occupied office_desk_2_storage)
    (not_occupied office_desk_3_storage)
    (not_occupied office_entrance_2)
    (not_occupied office_door_2)
    (not_occupied office_door_2)
    (not_occupied office_desk_5_storage)
    (not_occupied office_desk_2_cabinet)
    (not_occupied office_desk_3)
    (not_occupied office_desk_2)
    (not_occupied office_desk_1)
    (not_occupied office_corridor)
    (not_occupied office_desk_5)
    (not_occupied office_shelf_2)
    (not_occupied office_shelf_3)
    (not_occupied office_shelf_3)
    (not_occupied office_shelf_1)
    (not_occupied office_storage_1)
    (not_occupied office_desk_4_storage)
    (not_occupied office_desk_1_cabinet)


(connected main_door entrance) (= (distance  main_door entrance) 8)
(connected main_door main_entrance) (= (distance  main_door main_entrance) 9)
(connected main_door kitchen_sink) (= (distance  main_door kitchen_sink) 14)
(connected main_door kitchen_table_5) (= (distance  main_door kitchen_table_5) 16)
(connected main_door kitchen_chair) (= (distance  main_door kitchen_chair) 18)
(connected main_door kitchen_table_1) (= (distance  main_door kitchen_table_1) 20)
(connected main_door kitchen_corridor_2) (= (distance  main_door kitchen_corridor_2) 23)
(connected main_door kitchen_corridor) (= (distance  main_door kitchen_corridor) 25)
(connected main_door coffee_table_1) (= (distance  main_door coffee_table_1) 28)
(connected main_door corridor_centre) (= (distance  main_door corridor_centre) 34)
(connected main_door kitchen_table_4) (= (distance  main_door kitchen_table_4) 35)
(connected main_door kitchen_table_3) (= (distance  main_door kitchen_table_3) 40)
(connected kitchen_shelf microwave) (= (distance  kitchen_shelf microwave) 7)
(connected kitchen_shelf coffee_table_2) (= (distance  kitchen_shelf coffee_table_2) 9)
(connected kitchen_shelf coffee_table_1) (= (distance  kitchen_shelf coffee_table_1) 11)
(connected kitchen_shelf kitchen_corridor) (= (distance  kitchen_shelf kitchen_corridor) 17)
(connected kitchen_shelf kitchen_table_1) (= (distance  kitchen_shelf kitchen_table_1) 20)
(connected kitchen_shelf kitchen_table_5) (= (distance  kitchen_shelf kitchen_table_5) 28)
(connected microwave kitchen_counter) (= (distance  microwave kitchen_counter) 5)
(connected microwave coffee_table_1) (= (distance  microwave coffee_table_1) 6)
(connected microwave kitchen_shelf) (= (distance  microwave kitchen_shelf) 7)
(connected microwave coffee_table_2) (= (distance  microwave coffee_table_2) 9)
(connected microwave kitchen_corridor) (= (distance  microwave kitchen_corridor) 11)
(connected microwave kitchen_sink) (= (distance  microwave kitchen_sink) 12)
(connected microwave kitchen_table_1) (= (distance  microwave kitchen_table_1) 13)
(connected microwave entrance) (= (distance  microwave entrance) 19)
(connected microwave kitchen_hallway) (= (distance  microwave kitchen_hallway) 20)
(connected microwave kitchen_table_5) (= (distance  microwave kitchen_table_5) 21)
(connected microwave main_entrance) (= (distance  microwave main_entrance) 25)
(connected microwave kitchen_table_2) (= (distance  microwave kitchen_table_2) 27)
(connected kitchen_sink kitchen_counter) (= (distance  kitchen_sink kitchen_counter) 7)
(connected kitchen_sink entrance) (= (distance  kitchen_sink entrance) 8)
(connected kitchen_sink kitchen_table_1) (= (distance  kitchen_sink kitchen_table_1) 9)
(connected kitchen_sink kitchen_table_5) (= (distance  kitchen_sink kitchen_table_5) 12)
(connected kitchen_sink microwave) (= (distance  kitchen_sink microwave) 12)
(connected kitchen_sink kitchen_corridor) (= (distance  kitchen_sink kitchen_corridor) 13)
(connected kitchen_sink main_entrance) (= (distance  kitchen_sink main_entrance) 13)
(connected kitchen_sink main_door) (= (distance  kitchen_sink main_door) 14)
(connected kitchen_sink coffee_table_1) (= (distance  kitchen_sink coffee_table_1) 14)
(connected kitchen_sink kitchen_chair) (= (distance  kitchen_sink kitchen_chair) 16)
(connected kitchen_sink coffee_table_2) (= (distance  kitchen_sink coffee_table_2) 19)
(connected kitchen_sink kitchen_hallway) (= (distance  kitchen_sink kitchen_hallway) 21)
(connected kitchen_sink corridor_centre) (= (distance  kitchen_sink corridor_centre) 32)
(connected kitchen_sink fridge) (= (distance  kitchen_sink fridge) 33)
(connected kitchen_sink meeting_room_hallway) (= (distance  kitchen_sink meeting_room_hallway) 38)
(connected kitchen_sink office_door_2) (= (distance  kitchen_sink office_door_2) 55)
(connected kitchen_counter microwave) (= (distance  kitchen_counter microwave) 5)
(connected kitchen_counter kitchen_sink) (= (distance  kitchen_counter kitchen_sink) 7)
(connected kitchen_counter coffee_table_1) (= (distance  kitchen_counter coffee_table_1) 8)
(connected kitchen_counter kitchen_table_1) (= (distance  kitchen_counter kitchen_table_1) 10)
(connected kitchen_counter kitchen_corridor) (= (distance  kitchen_counter kitchen_corridor) 10)
(connected kitchen_counter coffee_table_2) (= (distance  kitchen_counter coffee_table_2) 13)
(connected kitchen_counter entrance) (= (distance  kitchen_counter entrance) 14)
(connected kitchen_counter kitchen_table_5) (= (distance  kitchen_counter kitchen_table_5) 16)
(connected kitchen_counter kitchen_hallway) (= (distance  kitchen_counter kitchen_hallway) 19)
(connected kitchen_counter main_entrance) (= (distance  kitchen_counter main_entrance) 20)
(connected kitchen_counter kitchen_table_2) (= (distance  kitchen_counter kitchen_table_2) 26)
(connected kitchen_counter kitchen_door_1) (= (distance  kitchen_counter kitchen_door_1) 36)
(connected kitchen_counter office_door_1) (= (distance  kitchen_counter office_door_1) 41)
(connected kitchen_counter office_desk_1) (= (distance  kitchen_counter office_desk_1) 50)
(connected kitchen_counter office_storage_1) (= (distance  kitchen_counter office_storage_1) 55)
(connected kitchen_counter office_desk_1_cabinet) (= (distance  kitchen_counter office_desk_1_cabinet) 57)
(connected entrance main_entrance) (= (distance  entrance main_entrance) 6)
(connected entrance kitchen_sink) (= (distance  entrance kitchen_sink) 8)
(connected entrance main_door) (= (distance  entrance main_door) 8)
(connected entrance kitchen_table_5) (= (distance  entrance kitchen_table_5) 9)
(connected entrance kitchen_table_1) (= (distance  entrance kitchen_table_1) 12)
(connected entrance kitchen_chair) (= (distance  entrance kitchen_chair) 12)
(connected entrance kitchen_counter) (= (distance  entrance kitchen_counter) 14)
(connected entrance kitchen_corridor) (= (distance  entrance kitchen_corridor) 18)
(connected entrance kitchen_corridor_2) (= (distance  entrance kitchen_corridor_2) 18)
(connected entrance microwave) (= (distance  entrance microwave) 19)
(connected entrance coffee_table_1) (= (distance  entrance coffee_table_1) 21)
(connected entrance coffee_table_2) (= (distance  entrance coffee_table_2) 27)
(connected entrance corridor_centre) (= (distance  entrance corridor_centre) 29)
(connected entrance corridor_shelf_1) (= (distance  entrance corridor_shelf_1) 37)
(connected main_office_desk main_office_cabinet) (= (distance  main_office_desk main_office_cabinet) 4)
(connected main_office_desk main_office_cupboard) (= (distance  main_office_desk main_office_cupboard) 6)
(connected main_office_desk main_office_corridor) (= (distance  main_office_desk main_office_corridor) 9)
(connected main_office_desk main_office_entrance) (= (distance  main_office_desk main_office_entrance) 13)
(connected main_office_desk main_office_doorway) (= (distance  main_office_desk main_office_doorway) 15)
(connected main_office_desk main_office_door) (= (distance  main_office_desk main_office_door) 20)
(connected main_office_desk corridor_shelf_2) (= (distance  main_office_desk corridor_shelf_2) 30)
(connected main_office_desk office_shelf_3) (= (distance  main_office_desk office_shelf_3) 53)
(connected main_office_cabinet main_office_desk) (= (distance  main_office_cabinet main_office_desk) 4)
(connected main_office_cabinet main_office_cupboard) (= (distance  main_office_cabinet main_office_cupboard) 7)
(connected main_office_cabinet main_office_corridor) (= (distance  main_office_cabinet main_office_corridor) 8)
(connected main_office_cabinet main_office_entrance) (= (distance  main_office_cabinet main_office_entrance) 13)
(connected main_office_cabinet main_office_doorway) (= (distance  main_office_cabinet main_office_doorway) 15)
(connected main_office_cabinet main_office_door) (= (distance  main_office_cabinet main_office_door) 20)
(connected main_office_cabinet corridor) (= (distance  main_office_cabinet corridor) 28)
(connected main_office_cabinet corridor_shelf_2) (= (distance  main_office_cabinet corridor_shelf_2) 29)
(connected main_office_cabinet kitchen_door_2) (= (distance  main_office_cabinet kitchen_door_2) 35)
(connected main_office_cabinet office_door_2) (= (distance  main_office_cabinet office_door_2) 42)
(connected main_office_cabinet office_shelf_3) (= (distance  main_office_cabinet office_shelf_3) 53)
(connected main_office_cabinet office_storage_2) (= (distance  main_office_cabinet office_storage_2) 55)
(connected main_entrance entrance) (= (distance  main_entrance entrance) 6)
(connected main_entrance kitchen_table_5) (= (distance  main_entrance kitchen_table_5) 8)
(connected main_entrance main_door) (= (distance  main_entrance main_door) 9)
(connected main_entrance kitchen_chair) (= (distance  main_entrance kitchen_chair) 9)
(connected main_entrance kitchen_sink) (= (distance  main_entrance kitchen_sink) 13)
(connected main_entrance kitchen_corridor_2) (= (distance  main_entrance kitchen_corridor_2) 14)
(connected main_entrance kitchen_table_1) (= (distance  main_entrance kitchen_table_1) 16)
(connected main_entrance kitchen_counter) (= (distance  main_entrance kitchen_counter) 20)
(connected main_entrance kitchen_corridor) (= (distance  main_entrance kitchen_corridor) 22)
(connected main_entrance corridor_centre) (= (distance  main_entrance corridor_centre) 24)
(connected main_entrance microwave) (= (distance  main_entrance microwave) 25)
(connected main_entrance kitchen_table_4) (= (distance  main_entrance kitchen_table_4) 25)
(connected main_entrance coffee_table_1) (= (distance  main_entrance coffee_table_1) 26)
(connected main_entrance kitchen_table_3) (= (distance  main_entrance kitchen_table_3) 31)
(connected main_entrance coffee_table_2) (= (distance  main_entrance coffee_table_2) 31)
(connected coffee_table_1 coffee_table_2) (= (distance  coffee_table_1 coffee_table_2) 6)
(connected coffee_table_1 microwave) (= (distance  coffee_table_1 microwave) 6)
(connected coffee_table_1 kitchen_corridor) (= (distance  coffee_table_1 kitchen_corridor) 6)
(connected coffee_table_1 kitchen_counter) (= (distance  coffee_table_1 kitchen_counter) 8)
(connected coffee_table_1 kitchen_shelf) (= (distance  coffee_table_1 kitchen_shelf) 11)
(connected coffee_table_1 kitchen_table_1) (= (distance  coffee_table_1 kitchen_table_1) 11)
(connected coffee_table_1 kitchen_sink) (= (distance  coffee_table_1 kitchen_sink) 14)
(connected coffee_table_1 kitchen_table_5) (= (distance  coffee_table_1 kitchen_table_5) 20)
(connected coffee_table_1 entrance) (= (distance  coffee_table_1 entrance) 21)
(connected coffee_table_1 main_entrance) (= (distance  coffee_table_1 main_entrance) 26)
(connected coffee_table_1 main_door) (= (distance  coffee_table_1 main_door) 28)
(connected coffee_table_2 coffee_table_1) (= (distance  coffee_table_2 coffee_table_1) 6)
(connected coffee_table_2 microwave) (= (distance  coffee_table_2 microwave) 9)
(connected coffee_table_2 kitchen_shelf) (= (distance  coffee_table_2 kitchen_shelf) 9)
(connected coffee_table_2 kitchen_counter) (= (distance  coffee_table_2 kitchen_counter) 13)
(connected coffee_table_2 kitchen_table_1) (= (distance  coffee_table_2 kitchen_table_1) 17)
(connected coffee_table_2 kitchen_sink) (= (distance  coffee_table_2 kitchen_sink) 19)
(connected coffee_table_2 kitchen_table_5) (= (distance  coffee_table_2 kitchen_table_5) 25)
(connected coffee_table_2 entrance) (= (distance  coffee_table_2 entrance) 27)
(connected coffee_table_2 main_entrance) (= (distance  coffee_table_2 main_entrance) 31)
(connected main_office_cupboard main_office_corridor) (= (distance  main_office_cupboard main_office_corridor) 4)
(connected main_office_cupboard main_office_desk) (= (distance  main_office_cupboard main_office_desk) 6)
(connected main_office_cupboard main_office_entrance) (= (distance  main_office_cupboard main_office_entrance) 6)
(connected main_office_cupboard main_office_cabinet) (= (distance  main_office_cupboard main_office_cabinet) 7)
(connected main_office_cupboard main_office_doorway) (= (distance  main_office_cupboard main_office_doorway) 9)
(connected main_office_cupboard main_office_door) (= (distance  main_office_cupboard main_office_door) 14)
(connected main_office_cupboard corridor) (= (distance  main_office_cupboard corridor) 22)
(connected main_office_cupboard corridor_shelf_2) (= (distance  main_office_cupboard corridor_shelf_2) 23)
(connected main_office_cupboard kitchen_door_2) (= (distance  main_office_cupboard kitchen_door_2) 29)
(connected main_office_cupboard office_door_2) (= (distance  main_office_cupboard office_door_2) 36)
(connected main_office_cupboard office_shelf_3) (= (distance  main_office_cupboard office_shelf_3) 47)
(connected main_office_cupboard office_storage_2) (= (distance  main_office_cupboard office_storage_2) 48)
(connected kitchen_table_1 kitchen_corridor) (= (distance  kitchen_table_1 kitchen_corridor) 6)
(connected kitchen_table_1 kitchen_table_5) (= (distance  kitchen_table_1 kitchen_table_5) 9)
(connected kitchen_table_1 kitchen_sink) (= (distance  kitchen_table_1 kitchen_sink) 9)
(connected kitchen_table_1 kitchen_counter) (= (distance  kitchen_table_1 kitchen_counter) 10)
(connected kitchen_table_1 coffee_table_1) (= (distance  kitchen_table_1 coffee_table_1) 11)
(connected kitchen_table_1 entrance) (= (distance  kitchen_table_1 entrance) 12)
(connected kitchen_table_1 microwave) (= (distance  kitchen_table_1 microwave) 13)
(connected kitchen_table_1 main_entrance) (= (distance  kitchen_table_1 main_entrance) 16)
(connected kitchen_table_1 coffee_table_2) (= (distance  kitchen_table_1 coffee_table_2) 17)
(connected kitchen_table_1 main_door) (= (distance  kitchen_table_1 main_door) 20)
(connected kitchen_table_1 kitchen_shelf) (= (distance  kitchen_table_1 kitchen_shelf) 20)
(connected kitchen_table_5 kitchen_chair) (= (distance  kitchen_table_5 kitchen_chair) 5)
(connected kitchen_table_5 main_entrance) (= (distance  kitchen_table_5 main_entrance) 8)
(connected kitchen_table_5 kitchen_table_1) (= (distance  kitchen_table_5 kitchen_table_1) 9)
(connected kitchen_table_5 entrance) (= (distance  kitchen_table_5 entrance) 9)
(connected kitchen_table_5 kitchen_sink) (= (distance  kitchen_table_5 kitchen_sink) 12)
(connected kitchen_table_5 main_door) (= (distance  kitchen_table_5 main_door) 16)
(connected kitchen_table_5 kitchen_counter) (= (distance  kitchen_table_5 kitchen_counter) 16)
(connected kitchen_table_5 coffee_table_1) (= (distance  kitchen_table_5 coffee_table_1) 20)
(connected kitchen_table_5 microwave) (= (distance  kitchen_table_5 microwave) 21)
(connected kitchen_table_5 kitchen_table_3) (= (distance  kitchen_table_5 kitchen_table_3) 23)
(connected kitchen_table_5 coffee_table_2) (= (distance  kitchen_table_5 coffee_table_2) 25)
(connected kitchen_table_5 meeting_room_hallway) (= (distance  kitchen_table_5 meeting_room_hallway) 27)
(connected kitchen_table_5 kitchen_shelf) (= (distance  kitchen_table_5 kitchen_shelf) 28)
(connected kitchen_table_5 kitchen_door_2) (= (distance  kitchen_table_5 kitchen_door_2) 39)
(connected kitchen_table_5 office_door_2) (= (distance  kitchen_table_5 office_door_2) 44)
(connected main_office_corridor main_office_cupboard) (= (distance  main_office_corridor main_office_cupboard) 4)
(connected main_office_corridor main_office_entrance) (= (distance  main_office_corridor main_office_entrance) 5)
(connected main_office_corridor main_office_doorway) (= (distance  main_office_corridor main_office_doorway) 7)
(connected main_office_corridor main_office_cabinet) (= (distance  main_office_corridor main_office_cabinet) 8)
(connected main_office_corridor main_office_desk) (= (distance  main_office_corridor main_office_desk) 9)
(connected main_office_corridor main_office_door) (= (distance  main_office_corridor main_office_door) 12)
(connected main_office_corridor corridor) (= (distance  main_office_corridor corridor) 21)
(connected main_office_corridor corridor_shelf_2) (= (distance  main_office_corridor corridor_shelf_2) 21)
(connected main_office_corridor kitchen_door_2) (= (distance  main_office_corridor kitchen_door_2) 28)
(connected main_office_corridor office_door_2) (= (distance  main_office_corridor office_door_2) 34)
(connected main_office_corridor office_entrance_2) (= (distance  main_office_corridor office_entrance_2) 36)
(connected main_office_corridor office_shelf_3) (= (distance  main_office_corridor office_shelf_3) 45)
(connected main_office_corridor office_storage_2) (= (distance  main_office_corridor office_storage_2) 47)
(connected kitchen_corridor kitchen_table_1) (= (distance  kitchen_corridor kitchen_table_1) 6)
(connected kitchen_corridor coffee_table_1) (= (distance  kitchen_corridor coffee_table_1) 6)
(connected kitchen_corridor kitchen_hallway) (= (distance  kitchen_corridor kitchen_hallway) 9)
(connected kitchen_corridor kitchen_counter) (= (distance  kitchen_corridor kitchen_counter) 10)
(connected kitchen_corridor microwave) (= (distance  kitchen_corridor microwave) 11)
(connected kitchen_corridor kitchen_sink) (= (distance  kitchen_corridor kitchen_sink) 13)
(connected kitchen_corridor kitchen_table_2) (= (distance  kitchen_corridor kitchen_table_2) 16)
(connected kitchen_corridor kitchen_shelf) (= (distance  kitchen_corridor kitchen_shelf) 17)
(connected kitchen_corridor entrance) (= (distance  kitchen_corridor entrance) 18)
(connected kitchen_corridor main_entrance) (= (distance  kitchen_corridor main_entrance) 22)
(connected kitchen_corridor main_door) (= (distance  kitchen_corridor main_door) 25)
(connected kitchen_corridor kitchen_door_1) (= (distance  kitchen_corridor kitchen_door_1) 26)
(connected kitchen_corridor office_door_1) (= (distance  kitchen_corridor office_door_1) 31)
(connected kitchen_corridor office_desk_1) (= (distance  kitchen_corridor office_desk_1) 40)
(connected kitchen_corridor office_storage_1) (= (distance  kitchen_corridor office_storage_1) 45)
(connected kitchen_corridor office_desk_1_cabinet) (= (distance  kitchen_corridor office_desk_1_cabinet) 47)
(connected kitchen_chair kitchen_table_5) (= (distance  kitchen_chair kitchen_table_5) 5)
(connected kitchen_chair kitchen_corridor_2) (= (distance  kitchen_chair kitchen_corridor_2) 6)
(connected kitchen_chair main_entrance) (= (distance  kitchen_chair main_entrance) 9)
(connected kitchen_chair entrance) (= (distance  kitchen_chair entrance) 12)
(connected kitchen_chair kitchen_sink) (= (distance  kitchen_chair kitchen_sink) 16)
(connected kitchen_chair kitchen_table_4) (= (distance  kitchen_chair kitchen_table_4) 16)
(connected kitchen_chair corridor_centre) (= (distance  kitchen_chair corridor_centre) 17)
(connected kitchen_chair main_door) (= (distance  kitchen_chair main_door) 18)
(connected kitchen_chair meeting_room_hallway) (= (distance  kitchen_chair meeting_room_hallway) 22)
(connected kitchen_chair corridor_shelf_1) (= (distance  kitchen_chair corridor_shelf_1) 25)
(connected kitchen_chair kitchen_door_1) (= (distance  kitchen_chair kitchen_door_1) 32)
(connected kitchen_chair kitchen_door_2) (= (distance  kitchen_chair kitchen_door_2) 34)
(connected kitchen_chair office_door_2) (= (distance  kitchen_chair office_door_2) 39)
(connected kitchen_chair office_desk_1_storage) (= (distance  kitchen_chair office_desk_1_storage) 42)
(connected meeting_room meeting_room_door) (= (distance  meeting_room meeting_room_door) 8)
(connected meeting_room meeting_room_hallway) (= (distance  meeting_room meeting_room_hallway) 15)
(connected meeting_room corridor_centre) (= (distance  meeting_room corridor_centre) 17)
(connected meeting_room corridor) (= (distance  meeting_room corridor) 18)
(connected meeting_room corridor_shelf_1) (= (distance  meeting_room corridor_shelf_1) 21)
(connected meeting_room kitchen_door_2) (= (distance  meeting_room kitchen_door_2) 24)
(connected meeting_room office_door_2) (= (distance  meeting_room office_door_2) 31)
(connected meeting_room office_desk_5) (= (distance  meeting_room office_desk_5) 40)
(connected meeting_room office_shelf_3) (= (distance  meeting_room office_shelf_3) 41)
(connected main_office_entrance main_office_doorway) (= (distance  main_office_entrance main_office_doorway) 3)
(connected main_office_entrance main_office_corridor) (= (distance  main_office_entrance main_office_corridor) 5)
(connected main_office_entrance main_office_cupboard) (= (distance  main_office_entrance main_office_cupboard) 6)
(connected main_office_entrance main_office_door) (= (distance  main_office_entrance main_office_door) 8)
(connected main_office_entrance main_office_desk) (= (distance  main_office_entrance main_office_desk) 13)
(connected main_office_entrance main_office_cabinet) (= (distance  main_office_entrance main_office_cabinet) 13)
(connected main_office_entrance corridor) (= (distance  main_office_entrance corridor) 16)
(connected main_office_entrance corridor_shelf_2) (= (distance  main_office_entrance corridor_shelf_2) 17)
(connected main_office_entrance kitchen_door_2) (= (distance  main_office_entrance kitchen_door_2) 23)
(connected main_office_entrance office_door_2) (= (distance  main_office_entrance office_door_2) 30)
(connected main_office_entrance office_entrance_2) (= (distance  main_office_entrance office_entrance_2) 31)
(connected main_office_entrance office_shelf_3) (= (distance  main_office_entrance office_shelf_3) 40)
(connected main_office_entrance office_storage_2) (= (distance  main_office_entrance office_storage_2) 42)
(connected main_office_doorway main_office_entrance) (= (distance  main_office_doorway main_office_entrance) 3)
(connected main_office_doorway main_office_door) (= (distance  main_office_doorway main_office_door) 5)
(connected main_office_doorway main_office_corridor) (= (distance  main_office_doorway main_office_corridor) 7)
(connected main_office_doorway main_office_cupboard) (= (distance  main_office_doorway main_office_cupboard) 9)
(connected main_office_doorway corridor) (= (distance  main_office_doorway corridor) 14)
(connected main_office_doorway corridor_shelf_2) (= (distance  main_office_doorway corridor_shelf_2) 14)
(connected main_office_doorway main_office_cabinet) (= (distance  main_office_doorway main_office_cabinet) 15)
(connected main_office_doorway main_office_desk) (= (distance  main_office_doorway main_office_desk) 15)
(connected main_office_doorway meeting_room_hallway) (= (distance  main_office_doorway meeting_room_hallway) 21)
(connected main_office_doorway kitchen_door_2) (= (distance  main_office_doorway kitchen_door_2) 21)
(connected main_office_doorway corridor_shelf_1) (= (distance  main_office_doorway corridor_shelf_1) 26)
(connected main_office_doorway office_door_2) (= (distance  main_office_doorway office_door_2) 27)
(connected main_office_doorway corridor_centre) (= (distance  main_office_doorway corridor_centre) 29)
(connected main_office_doorway office_entrance_2) (= (distance  main_office_doorway office_entrance_2) 29)
(connected main_office_doorway office_shelf_3) (= (distance  main_office_doorway office_shelf_3) 38)
(connected main_office_doorway office_storage_2) (= (distance  main_office_doorway office_storage_2) 40)
(connected kitchen_corridor_2 kitchen_chair) (= (distance  kitchen_corridor_2 kitchen_chair) 6)
(connected kitchen_corridor_2 corridor_centre) (= (distance  kitchen_corridor_2 corridor_centre) 11)
(connected kitchen_corridor_2 kitchen_table_4) (= (distance  kitchen_corridor_2 kitchen_table_4) 12)
(connected kitchen_corridor_2 meeting_room_door) (= (distance  kitchen_corridor_2 meeting_room_door) 14)
(connected kitchen_corridor_2 main_entrance) (= (distance  kitchen_corridor_2 main_entrance) 14)
(connected kitchen_corridor_2 meeting_room_hallway) (= (distance  kitchen_corridor_2 meeting_room_hallway) 17)
(connected kitchen_corridor_2 entrance) (= (distance  kitchen_corridor_2 entrance) 18)
(connected kitchen_corridor_2 corridor_shelf_1) (= (distance  kitchen_corridor_2 corridor_shelf_1) 19)
(connected kitchen_corridor_2 main_door) (= (distance  kitchen_corridor_2 main_door) 23)
(connected kitchen_corridor_2 corridor) (= (distance  kitchen_corridor_2 corridor) 26)
(connected kitchen_corridor_2 kitchen_door_2) (= (distance  kitchen_corridor_2 kitchen_door_2) 29)
(connected kitchen_corridor_2 main_office_door) (= (distance  kitchen_corridor_2 main_office_door) 30)
(connected kitchen_corridor_2 corridor_shelf_2) (= (distance  kitchen_corridor_2 corridor_shelf_2) 33)
(connected kitchen_corridor_2 office_desk_5_storage) (= (distance  kitchen_corridor_2 office_desk_5_storage) 42)
(connected kitchen_hallway coffee_table_4) (= (distance  kitchen_hallway coffee_table_4) 5)
(connected kitchen_hallway kitchen_table_2) (= (distance  kitchen_hallway kitchen_table_2) 7)
(connected kitchen_hallway kitchen_corridor) (= (distance  kitchen_hallway kitchen_corridor) 9)
(connected kitchen_hallway fridge) (= (distance  kitchen_hallway fridge) 13)
(connected kitchen_hallway kitchen_table_3) (= (distance  kitchen_hallway kitchen_table_3) 13)
(connected kitchen_hallway kitchen_door_1) (= (distance  kitchen_hallway kitchen_door_1) 17)
(connected kitchen_hallway kitchen_counter) (= (distance  kitchen_hallway kitchen_counter) 19)
(connected kitchen_hallway microwave) (= (distance  kitchen_hallway microwave) 20)
(connected kitchen_hallway kitchen_sink) (= (distance  kitchen_hallway kitchen_sink) 21)
(connected kitchen_hallway office_door_1) (= (distance  kitchen_hallway office_door_1) 22)
(connected kitchen_hallway office_desk_1) (= (distance  kitchen_hallway office_desk_1) 31)
(connected kitchen_hallway office_storage_1) (= (distance  kitchen_hallway office_storage_1) 36)
(connected kitchen_hallway office_desk_1_cabinet) (= (distance  kitchen_hallway office_desk_1_cabinet) 38)
(connected meeting_room_door meeting_room) (= (distance  meeting_room_door meeting_room) 8)
(connected meeting_room_door meeting_room_hallway) (= (distance  meeting_room_door meeting_room_hallway) 8)
(connected meeting_room_door corridor_centre) (= (distance  meeting_room_door corridor_centre) 12)
(connected meeting_room_door corridor) (= (distance  meeting_room_door corridor) 13)
(connected meeting_room_door corridor_shelf_1) (= (distance  meeting_room_door corridor_shelf_1) 13)
(connected meeting_room_door kitchen_corridor_2) (= (distance  meeting_room_door kitchen_corridor_2) 14)
(connected meeting_room_door main_office_door) (= (distance  meeting_room_door main_office_door) 16)
(connected meeting_room_door kitchen_door_2) (= (distance  meeting_room_door kitchen_door_2) 17)
(connected meeting_room_door kitchen_table_4) (= (distance  meeting_room_door kitchen_table_4) 19)
(connected meeting_room_door corridor_shelf_2) (= (distance  meeting_room_door corridor_shelf_2) 20)
(connected meeting_room_door office_door_2) (= (distance  meeting_room_door office_door_2) 23)
(connected meeting_room_door office_desk_5) (= (distance  meeting_room_door office_desk_5) 33)
(connected meeting_room_door office_desk_1_storage) (= (distance  meeting_room_door office_desk_1_storage) 51)
(connected main_office_door main_office_doorway) (= (distance  main_office_door main_office_doorway) 5)
(connected main_office_door main_office_entrance) (= (distance  main_office_door main_office_entrance) 8)
(connected main_office_door corridor_shelf_2) (= (distance  main_office_door corridor_shelf_2) 9)
(connected main_office_door corridor) (= (distance  main_office_door corridor) 9)
(connected main_office_door main_office_corridor) (= (distance  main_office_door main_office_corridor) 12)
(connected main_office_door main_office_cupboard) (= (distance  main_office_door main_office_cupboard) 14)
(connected main_office_door kitchen_door_2) (= (distance  main_office_door kitchen_door_2) 16)
(connected main_office_door meeting_room_door) (= (distance  main_office_door meeting_room_door) 16)
(connected main_office_door meeting_room_hallway) (= (distance  main_office_door meeting_room_hallway) 18)
(connected main_office_door main_office_cabinet) (= (distance  main_office_door main_office_cabinet) 20)
(connected main_office_door main_office_desk) (= (distance  main_office_door main_office_desk) 20)
(connected main_office_door office_door_2) (= (distance  main_office_door office_door_2) 22)
(connected main_office_door corridor_shelf_1) (= (distance  main_office_door corridor_shelf_1) 23)
(connected main_office_door office_entrance_2) (= (distance  main_office_door office_entrance_2) 24)
(connected main_office_door corridor_centre) (= (distance  main_office_door corridor_centre) 27)
(connected main_office_door office_desk_3) (= (distance  main_office_door office_desk_3) 30)
(connected main_office_door kitchen_corridor_2) (= (distance  main_office_door kitchen_corridor_2) 30)
(connected main_office_door office_shelf_3) (= (distance  main_office_door office_shelf_3) 33)
(connected main_office_door kitchen_table_4) (= (distance  main_office_door kitchen_table_4) 34)
(connected main_office_door office_storage_2) (= (distance  main_office_door office_storage_2) 35)
(connected coffee_table_3 coffee_table_4) (= (distance  coffee_table_3 coffee_table_4) 6)
(connected coffee_table_3 fridge) (= (distance  coffee_table_3 fridge) 9)
(connected coffee_table_3 kitchen_table_2) (= (distance  coffee_table_3 kitchen_table_2) 13)
(connected coffee_table_3 kitchen_door_1) (= (distance  coffee_table_3 kitchen_door_1) 16)
(connected coffee_table_3 kitchen_table_3) (= (distance  coffee_table_3 kitchen_table_3) 20)
(connected coffee_table_3 office_entrance_1) (= (distance  coffee_table_3 office_entrance_1) 24)
(connected coffee_table_3 office_desk_2_cabinet) (= (distance  coffee_table_3 office_desk_2_cabinet) 30)
(connected coffee_table_3 office_shelf_1) (= (distance  coffee_table_3 office_shelf_1) 37)
(connected coffee_table_3 office_desk_4_storage) (= (distance  coffee_table_3 office_desk_4_storage) 41)
(connected coffee_table_4 kitchen_hallway) (= (distance  coffee_table_4 kitchen_hallway) 5)
(connected coffee_table_4 coffee_table_3) (= (distance  coffee_table_4 coffee_table_3) 6)
(connected coffee_table_4 kitchen_table_2) (= (distance  coffee_table_4 kitchen_table_2) 8)
(connected coffee_table_4 fridge) (= (distance  coffee_table_4 fridge) 8)
(connected coffee_table_4 kitchen_door_1) (= (distance  coffee_table_4 kitchen_door_1) 14)
(connected coffee_table_4 kitchen_table_3) (= (distance  coffee_table_4 kitchen_table_3) 15)
(connected coffee_table_4 office_door_1) (= (distance  coffee_table_4 office_door_1) 19)
(connected coffee_table_4 office_desk_1) (= (distance  coffee_table_4 office_desk_1) 28)
(connected coffee_table_4 office_storage_1) (= (distance  coffee_table_4 office_storage_1) 34)
(connected coffee_table_4 office_shelf_1) (= (distance  coffee_table_4 office_shelf_1) 35)
(connected coffee_table_4 office_desk_1_cabinet) (= (distance  coffee_table_4 office_desk_1_cabinet) 35)
(connected kitchen_table_2 kitchen_table_3) (= (distance  kitchen_table_2 kitchen_table_3) 7)
(connected kitchen_table_2 kitchen_hallway) (= (distance  kitchen_table_2 kitchen_hallway) 7)
(connected kitchen_table_2 coffee_table_4) (= (distance  kitchen_table_2 coffee_table_4) 8)
(connected kitchen_table_2 fridge) (= (distance  kitchen_table_2 fridge) 10)
(connected kitchen_table_2 kitchen_door_1) (= (distance  kitchen_table_2 kitchen_door_1) 11)
(connected kitchen_table_2 coffee_table_3) (= (distance  kitchen_table_2 coffee_table_3) 13)
(connected kitchen_table_2 office_door_1) (= (distance  kitchen_table_2 office_door_1) 16)
(connected kitchen_table_2 kitchen_corridor) (= (distance  kitchen_table_2 kitchen_corridor) 16)
(connected kitchen_table_2 office_desk_1) (= (distance  kitchen_table_2 office_desk_1) 25)
(connected kitchen_table_2 kitchen_counter) (= (distance  kitchen_table_2 kitchen_counter) 26)
(connected kitchen_table_2 microwave) (= (distance  kitchen_table_2 microwave) 27)
(connected kitchen_table_2 office_storage_1) (= (distance  kitchen_table_2 office_storage_1) 29)
(connected kitchen_table_2 office_desk_1_cabinet) (= (distance  kitchen_table_2 office_desk_1_cabinet) 32)
(connected corridor_centre kitchen_table_4) (= (distance  corridor_centre kitchen_table_4) 7)
(connected corridor_centre corridor_shelf_1) (= (distance  corridor_centre corridor_shelf_1) 9)
(connected corridor_centre meeting_room_hallway) (= (distance  corridor_centre meeting_room_hallway) 9)
(connected corridor_centre kitchen_corridor_2) (= (distance  corridor_centre kitchen_corridor_2) 11)
(connected corridor_centre meeting_room_door) (= (distance  corridor_centre meeting_room_door) 12)
(connected corridor_centre kitchen_chair) (= (distance  corridor_centre kitchen_chair) 17)
(connected corridor_centre meeting_room) (= (distance  corridor_centre meeting_room) 17)
(connected corridor_centre corridor) (= (distance  corridor_centre corridor) 20)
(connected corridor_centre kitchen_door_2) (= (distance  corridor_centre kitchen_door_2) 21)
(connected corridor_centre main_entrance) (= (distance  corridor_centre main_entrance) 24)
(connected corridor_centre corridor_shelf_2) (= (distance  corridor_centre corridor_shelf_2) 27)
(connected corridor_centre main_office_door) (= (distance  corridor_centre main_office_door) 27)
(connected corridor_centre main_office_doorway) (= (distance  corridor_centre main_office_doorway) 29)
(connected corridor_centre entrance) (= (distance  corridor_centre entrance) 29)
(connected corridor_centre kitchen_door_1) (= (distance  corridor_centre kitchen_door_1) 29)
(connected corridor_centre kitchen_sink) (= (distance  corridor_centre kitchen_sink) 32)
(connected corridor_centre office_desk_5_storage) (= (distance  corridor_centre office_desk_5_storage) 33)
(connected corridor_centre main_door) (= (distance  corridor_centre main_door) 34)
(connected meeting_room_hallway corridor_shelf_1) (= (distance  meeting_room_hallway corridor_shelf_1) 6)
(connected meeting_room_hallway meeting_room_door) (= (distance  meeting_room_hallway meeting_room_door) 8)
(connected meeting_room_hallway corridor_centre) (= (distance  meeting_room_hallway corridor_centre) 9)
(connected meeting_room_hallway corridor) (= (distance  meeting_room_hallway corridor) 10)
(connected meeting_room_hallway kitchen_door_2) (= (distance  meeting_room_hallway kitchen_door_2) 12)
(connected meeting_room_hallway meeting_room) (= (distance  meeting_room_hallway meeting_room) 15)
(connected meeting_room_hallway kitchen_table_4) (= (distance  meeting_room_hallway kitchen_table_4) 16)
(connected meeting_room_hallway office_door_2) (= (distance  meeting_room_hallway office_door_2) 17)
(connected meeting_room_hallway kitchen_corridor_2) (= (distance  meeting_room_hallway kitchen_corridor_2) 17)
(connected meeting_room_hallway corridor_shelf_2) (= (distance  meeting_room_hallway corridor_shelf_2) 17)
(connected meeting_room_hallway main_office_door) (= (distance  meeting_room_hallway main_office_door) 18)
(connected meeting_room_hallway main_office_doorway) (= (distance  meeting_room_hallway main_office_doorway) 21)
(connected meeting_room_hallway kitchen_chair) (= (distance  meeting_room_hallway kitchen_chair) 22)
(connected meeting_room_hallway office_desk_5_storage) (= (distance  meeting_room_hallway office_desk_5_storage) 25)
(connected meeting_room_hallway office_desk_5) (= (distance  meeting_room_hallway office_desk_5) 26)
(connected meeting_room_hallway kitchen_table_5) (= (distance  meeting_room_hallway kitchen_table_5) 27)
(connected meeting_room_hallway kitchen_table_3) (= (distance  meeting_room_hallway kitchen_table_3) 28)
(connected meeting_room_hallway kitchen_door_1) (= (distance  meeting_room_hallway kitchen_door_1) 38)
(connected meeting_room_hallway kitchen_sink) (= (distance  meeting_room_hallway kitchen_sink) 38)
(connected corridor corridor_shelf_2) (= (distance  corridor corridor_shelf_2) 7)
(connected corridor kitchen_door_2) (= (distance  corridor kitchen_door_2) 7)
(connected corridor main_office_door) (= (distance  corridor main_office_door) 9)
(connected corridor meeting_room_hallway) (= (distance  corridor meeting_room_hallway) 10)
(connected corridor meeting_room_door) (= (distance  corridor meeting_room_door) 13)
(connected corridor main_office_doorway) (= (distance  corridor main_office_doorway) 14)
(connected corridor office_door_2) (= (distance  corridor office_door_2) 14)
(connected corridor corridor_shelf_1) (= (distance  corridor corridor_shelf_1) 14)
(connected corridor office_entrance_2) (= (distance  corridor office_entrance_2) 15)
(connected corridor main_office_entrance) (= (distance  corridor main_office_entrance) 16)
(connected corridor meeting_room) (= (distance  corridor meeting_room) 18)
(connected corridor corridor_centre) (= (distance  corridor corridor_centre) 20)
(connected corridor main_office_corridor) (= (distance  corridor main_office_corridor) 21)
(connected corridor main_office_cupboard) (= (distance  corridor main_office_cupboard) 22)
(connected corridor office_desk_5) (= (distance  corridor office_desk_5) 23)
(connected corridor office_shelf_3) (= (distance  corridor office_shelf_3) 25)
(connected corridor kitchen_corridor_2) (= (distance  corridor kitchen_corridor_2) 26)
(connected corridor office_storage_2) (= (distance  corridor office_storage_2) 26)
(connected corridor kitchen_table_4) (= (distance  corridor kitchen_table_4) 27)
(connected corridor main_office_cabinet) (= (distance  corridor main_office_cabinet) 28)
(connected kitchen_table_4 corridor_centre) (= (distance  kitchen_table_4 corridor_centre) 7)
(connected kitchen_table_4 kitchen_corridor_2) (= (distance  kitchen_table_4 kitchen_corridor_2) 12)
(connected kitchen_table_4 corridor_shelf_1) (= (distance  kitchen_table_4 corridor_shelf_1) 14)
(connected kitchen_table_4 kitchen_chair) (= (distance  kitchen_table_4 kitchen_chair) 16)
(connected kitchen_table_4 meeting_room_hallway) (= (distance  kitchen_table_4 meeting_room_hallway) 16)
(connected kitchen_table_4 meeting_room_door) (= (distance  kitchen_table_4 meeting_room_door) 19)
(connected kitchen_table_4 kitchen_door_1) (= (distance  kitchen_table_4 kitchen_door_1) 22)
(connected kitchen_table_4 main_entrance) (= (distance  kitchen_table_4 main_entrance) 25)
(connected kitchen_table_4 corridor) (= (distance  kitchen_table_4 corridor) 27)
(connected kitchen_table_4 kitchen_door_2) (= (distance  kitchen_table_4 kitchen_door_2) 27)
(connected kitchen_table_4 office_desk_1_storage) (= (distance  kitchen_table_4 office_desk_1_storage) 32)
(connected kitchen_table_4 corridor_shelf_2) (= (distance  kitchen_table_4 corridor_shelf_2) 34)
(connected kitchen_table_4 main_office_door) (= (distance  kitchen_table_4 main_office_door) 34)
(connected kitchen_table_4 main_door) (= (distance  kitchen_table_4 main_door) 35)
(connected fridge kitchen_door_1) (= (distance  fridge kitchen_door_1) 8)
(connected fridge coffee_table_4) (= (distance  fridge coffee_table_4) 8)
(connected fridge coffee_table_3) (= (distance  fridge coffee_table_3) 9)
(connected fridge kitchen_table_2) (= (distance  fridge kitchen_table_2) 10)
(connected fridge office_door_1) (= (distance  fridge office_door_1) 12)
(connected fridge kitchen_hallway) (= (distance  fridge kitchen_hallway) 13)
(connected fridge kitchen_table_3) (= (distance  fridge kitchen_table_3) 14)
(connected fridge office_entrance_1) (= (distance  fridge office_entrance_1) 15)
(connected fridge office_desk_2_cabinet) (= (distance  fridge office_desk_2_cabinet) 21)
(connected fridge office_storage_1) (= (distance  fridge office_storage_1) 27)
(connected fridge office_shelf_1) (= (distance  fridge office_shelf_1) 28)
(connected fridge office_desk_4_storage) (= (distance  fridge office_desk_4_storage) 33)
(connected fridge kitchen_sink) (= (distance  fridge kitchen_sink) 33)
(connected fridge corridor_shelf_1) (= (distance  fridge corridor_shelf_1) 39)
(connected fridge kitchen_door_2) (= (distance  fridge kitchen_door_2) 51)
(connected corridor_shelf_2 corridor) (= (distance  corridor_shelf_2 corridor) 7)
(connected corridor_shelf_2 kitchen_door_2) (= (distance  corridor_shelf_2 kitchen_door_2) 9)
(connected corridor_shelf_2 main_office_door) (= (distance  corridor_shelf_2 main_office_door) 9)
(connected corridor_shelf_2 office_door_2) (= (distance  corridor_shelf_2 office_door_2) 14)
(connected corridor_shelf_2 main_office_doorway) (= (distance  corridor_shelf_2 main_office_doorway) 14)
(connected corridor_shelf_2 main_office_entrance) (= (distance  corridor_shelf_2 main_office_entrance) 17)
(connected corridor_shelf_2 office_entrance_2) (= (distance  corridor_shelf_2 office_entrance_2) 17)
(connected corridor_shelf_2 meeting_room_hallway) (= (distance  corridor_shelf_2 meeting_room_hallway) 17)
(connected corridor_shelf_2 meeting_room_door) (= (distance  corridor_shelf_2 meeting_room_door) 20)
(connected corridor_shelf_2 corridor_shelf_1) (= (distance  corridor_shelf_2 corridor_shelf_1) 20)
(connected corridor_shelf_2 main_office_corridor) (= (distance  corridor_shelf_2 main_office_corridor) 21)
(connected corridor_shelf_2 office_desk_3) (= (distance  corridor_shelf_2 office_desk_3) 23)
(connected corridor_shelf_2 main_office_cupboard) (= (distance  corridor_shelf_2 main_office_cupboard) 23)
(connected corridor_shelf_2 corridor_centre) (= (distance  corridor_shelf_2 corridor_centre) 27)
(connected corridor_shelf_2 main_office_cabinet) (= (distance  corridor_shelf_2 main_office_cabinet) 29)
(connected corridor_shelf_2 main_office_desk) (= (distance  corridor_shelf_2 main_office_desk) 30)
(connected corridor_shelf_2 office_shelf_2) (= (distance  corridor_shelf_2 office_shelf_2) 32)
(connected corridor_shelf_2 kitchen_corridor_2) (= (distance  corridor_shelf_2 kitchen_corridor_2) 33)
(connected corridor_shelf_2 kitchen_table_4) (= (distance  corridor_shelf_2 kitchen_table_4) 34)
(connected corridor_shelf_2 kitchen_table_3) (= (distance  corridor_shelf_2 kitchen_table_3) 45)
(connected kitchen_table_3 kitchen_table_2) (= (distance  kitchen_table_3 kitchen_table_2) 7)
(connected kitchen_table_3 kitchen_door_1) (= (distance  kitchen_table_3 kitchen_door_1) 11)
(connected kitchen_table_3 kitchen_hallway) (= (distance  kitchen_table_3 kitchen_hallway) 13)
(connected kitchen_table_3 office_door_1) (= (distance  kitchen_table_3 office_door_1) 14)
(connected kitchen_table_3 fridge) (= (distance  kitchen_table_3 fridge) 14)
(connected kitchen_table_3 coffee_table_4) (= (distance  kitchen_table_3 coffee_table_4) 15)
(connected kitchen_table_3 coffee_table_3) (= (distance  kitchen_table_3 coffee_table_3) 20)
(connected kitchen_table_3 office_desk_1_storage) (= (distance  kitchen_table_3 office_desk_1_storage) 21)
(connected kitchen_table_3 kitchen_table_5) (= (distance  kitchen_table_3 kitchen_table_5) 23)
(connected kitchen_table_3 corridor_shelf_1) (= (distance  kitchen_table_3 corridor_shelf_1) 25)
(connected kitchen_table_3 meeting_room_hallway) (= (distance  kitchen_table_3 meeting_room_hallway) 28)
(connected kitchen_table_3 main_entrance) (= (distance  kitchen_table_3 main_entrance) 31)
(connected kitchen_table_3 kitchen_door_2) (= (distance  kitchen_table_3 kitchen_door_2) 38)
(connected kitchen_table_3 corridor) (= (distance  kitchen_table_3 corridor) 38)
(connected kitchen_table_3 main_door) (= (distance  kitchen_table_3 main_door) 40)
(connected kitchen_table_3 corridor_shelf_2) (= (distance  kitchen_table_3 corridor_shelf_2) 45)
(connected corridor_shelf_1 meeting_room_hallway) (= (distance  corridor_shelf_1 meeting_room_hallway) 6)
(connected corridor_shelf_1 corridor_centre) (= (distance  corridor_shelf_1 corridor_centre) 9)
(connected corridor_shelf_1 kitchen_door_2) (= (distance  corridor_shelf_1 kitchen_door_2) 13)
(connected corridor_shelf_1 meeting_room_door) (= (distance  corridor_shelf_1 meeting_room_door) 13)
(connected corridor_shelf_1 kitchen_table_4) (= (distance  corridor_shelf_1 kitchen_table_4) 14)
(connected corridor_shelf_1 corridor) (= (distance  corridor_shelf_1 corridor) 14)
(connected corridor_shelf_1 kitchen_corridor_2) (= (distance  corridor_shelf_1 kitchen_corridor_2) 19)
(connected corridor_shelf_1 corridor_shelf_2) (= (distance  corridor_shelf_1 corridor_shelf_2) 20)
(connected corridor_shelf_1 meeting_room) (= (distance  corridor_shelf_1 meeting_room) 21)
(connected corridor_shelf_1 main_office_door) (= (distance  corridor_shelf_1 main_office_door) 23)
(connected corridor_shelf_1 kitchen_chair) (= (distance  corridor_shelf_1 kitchen_chair) 25)
(connected corridor_shelf_1 kitchen_table_3) (= (distance  corridor_shelf_1 kitchen_table_3) 25)
(connected corridor_shelf_1 main_office_doorway) (= (distance  corridor_shelf_1 main_office_doorway) 26)
(connected corridor_shelf_1 kitchen_door_1) (= (distance  corridor_shelf_1 kitchen_door_1) 35)
(connected corridor_shelf_1 entrance) (= (distance  corridor_shelf_1 entrance) 37)
(connected corridor_shelf_1 fridge) (= (distance  corridor_shelf_1 fridge) 39)
(connected kitchen_door_2 office_door_2) (= (distance  kitchen_door_2 office_door_2) 7)
(connected kitchen_door_2 corridor) (= (distance  kitchen_door_2 corridor) 7)
(connected kitchen_door_2 office_entrance_2) (= (distance  kitchen_door_2 office_entrance_2) 8)
(connected kitchen_door_2 corridor_shelf_2) (= (distance  kitchen_door_2 corridor_shelf_2) 9)
(connected kitchen_door_2 meeting_room_hallway) (= (distance  kitchen_door_2 meeting_room_hallway) 12)
(connected kitchen_door_2 corridor_shelf_1) (= (distance  kitchen_door_2 corridor_shelf_1) 13)
(connected kitchen_door_2 office_desk_3) (= (distance  kitchen_door_2 office_desk_3) 14)
(connected kitchen_door_2 office_desk_5) (= (distance  kitchen_door_2 office_desk_5) 16)
(connected kitchen_door_2 main_office_door) (= (distance  kitchen_door_2 main_office_door) 16)
(connected kitchen_door_2 meeting_room_door) (= (distance  kitchen_door_2 meeting_room_door) 17)
(connected kitchen_door_2 office_shelf_3) (= (distance  kitchen_door_2 office_shelf_3) 18)
(connected kitchen_door_2 office_storage_2) (= (distance  kitchen_door_2 office_storage_2) 19)
(connected kitchen_door_2 corridor_centre) (= (distance  kitchen_door_2 corridor_centre) 21)
(connected kitchen_door_2 main_office_doorway) (= (distance  kitchen_door_2 main_office_doorway) 21)
(connected kitchen_door_2 main_office_entrance) (= (distance  kitchen_door_2 main_office_entrance) 23)
(connected kitchen_door_2 office_shelf_2) (= (distance  kitchen_door_2 office_shelf_2) 24)
(connected kitchen_door_2 meeting_room) (= (distance  kitchen_door_2 meeting_room) 24)
(connected kitchen_door_2 kitchen_table_4) (= (distance  kitchen_door_2 kitchen_table_4) 27)
(connected kitchen_door_2 main_office_corridor) (= (distance  kitchen_door_2 main_office_corridor) 28)
(connected kitchen_door_2 kitchen_corridor_2) (= (distance  kitchen_door_2 kitchen_corridor_2) 29)
(connected kitchen_door_1 office_door_1) (= (distance  kitchen_door_1 office_door_1) 5)
(connected kitchen_door_1 fridge) (= (distance  kitchen_door_1 fridge) 8)
(connected kitchen_door_1 office_entrance_1) (= (distance  kitchen_door_1 office_entrance_1) 8)
(connected kitchen_door_1 office_desk_1_storage) (= (distance  kitchen_door_1 office_desk_1_storage) 11)
(connected kitchen_door_1 kitchen_table_3) (= (distance  kitchen_door_1 kitchen_table_3) 11)
(connected kitchen_door_1 kitchen_table_2) (= (distance  kitchen_door_1 kitchen_table_2) 11)
(connected kitchen_door_1 office_desk_2_cabinet) (= (distance  kitchen_door_1 office_desk_2_cabinet) 14)
(connected kitchen_door_1 office_desk_1) (= (distance  kitchen_door_1 office_desk_1) 14)
(connected kitchen_door_1 coffee_table_4) (= (distance  kitchen_door_1 coffee_table_4) 14)
(connected kitchen_door_1 coffee_table_3) (= (distance  kitchen_door_1 coffee_table_3) 16)
(connected kitchen_door_1 kitchen_hallway) (= (distance  kitchen_door_1 kitchen_hallway) 17)
(connected kitchen_door_1 office_storage_1) (= (distance  kitchen_door_1 office_storage_1) 20)
(connected kitchen_door_1 office_shelf_1) (= (distance  kitchen_door_1 office_shelf_1) 20)
(connected kitchen_door_1 office_desk_1_cabinet) (= (distance  kitchen_door_1 office_desk_1_cabinet) 21)
(connected kitchen_door_1 kitchen_table_4) (= (distance  kitchen_door_1 kitchen_table_4) 22)
(connected kitchen_door_1 office_desk_4_storage) (= (distance  kitchen_door_1 office_desk_4_storage) 25)
(connected kitchen_door_1 kitchen_corridor) (= (distance  kitchen_door_1 kitchen_corridor) 26)
(connected kitchen_door_1 corridor_centre) (= (distance  kitchen_door_1 corridor_centre) 29)
(connected kitchen_door_1 kitchen_chair) (= (distance  kitchen_door_1 kitchen_chair) 32)
(connected kitchen_door_1 corridor_shelf_1) (= (distance  kitchen_door_1 corridor_shelf_1) 35)
(connected office_door_1 kitchen_door_1) (= (distance  office_door_1 kitchen_door_1) 5)
(connected office_door_1 office_entrance_1) (= (distance  office_door_1 office_entrance_1) 5)
(connected office_door_1 office_desk_1_storage) (= (distance  office_door_1 office_desk_1_storage) 8)
(connected office_door_1 office_desk_1) (= (distance  office_door_1 office_desk_1) 9)
(connected office_door_1 office_desk_2_cabinet) (= (distance  office_door_1 office_desk_2_cabinet) 10)
(connected office_door_1 fridge) (= (distance  office_door_1 fridge) 12)
(connected office_door_1 kitchen_table_3) (= (distance  office_door_1 kitchen_table_3) 14)
(connected office_door_1 office_storage_1) (= (distance  office_door_1 office_storage_1) 15)
(connected office_door_1 kitchen_table_2) (= (distance  office_door_1 kitchen_table_2) 16)
(connected office_door_1 office_desk_1_cabinet) (= (distance  office_door_1 office_desk_1_cabinet) 16)
(connected office_door_1 office_shelf_1) (= (distance  office_door_1 office_shelf_1) 16)
(connected office_door_1 coffee_table_4) (= (distance  office_door_1 coffee_table_4) 19)
(connected office_door_1 office_desk_4_storage) (= (distance  office_door_1 office_desk_4_storage) 21)
(connected office_door_1 kitchen_hallway) (= (distance  office_door_1 kitchen_hallway) 22)
(connected office_door_1 kitchen_corridor) (= (distance  office_door_1 kitchen_corridor) 31)
(connected office_door_1 office_shelf_2) (= (distance  office_door_1 office_shelf_2) 34)
(connected office_door_1 kitchen_counter) (= (distance  office_door_1 kitchen_counter) 41)
(connected office_entrance_1 office_door_1) (= (distance  office_entrance_1 office_door_1) 5)
(connected office_entrance_1 office_desk_2_cabinet) (= (distance  office_entrance_1 office_desk_2_cabinet) 6)
(connected office_entrance_1 kitchen_door_1) (= (distance  office_entrance_1 kitchen_door_1) 8)
(connected office_entrance_1 office_desk_1) (= (distance  office_entrance_1 office_desk_1) 12)
(connected office_entrance_1 office_desk_1_storage) (= (distance  office_entrance_1 office_desk_1_storage) 13)
(connected office_entrance_1 office_shelf_1) (= (distance  office_entrance_1 office_shelf_1) 13)
(connected office_entrance_1 office_storage_1) (= (distance  office_entrance_1 office_storage_1) 14)
(connected office_entrance_1 fridge) (= (distance  office_entrance_1 fridge) 15)
(connected office_entrance_1 office_desk_4_storage) (= (distance  office_entrance_1 office_desk_4_storage) 17)
(connected office_entrance_1 office_desk_1_cabinet) (= (distance  office_entrance_1 office_desk_1_cabinet) 17)
(connected office_entrance_1 coffee_table_3) (= (distance  office_entrance_1 coffee_table_3) 24)
(connected office_desk_2_storage office_desk_3_storage) (= (distance  office_desk_2_storage office_desk_3_storage) 6)
(connected office_desk_2_storage office_desk_2) (= (distance  office_desk_2_storage office_desk_2) 6)
(connected office_desk_2_storage office_corridor) (= (distance  office_desk_2_storage office_corridor) 10)
(connected office_desk_2_storage office_desk_4_storage) (= (distance  office_desk_2_storage office_desk_4_storage) 16)
(connected office_desk_2_storage office_shelf_2) (= (distance  office_desk_2_storage office_shelf_2) 16)
(connected office_desk_2_storage office_storage_2) (= (distance  office_desk_2_storage office_storage_2) 25)
(connected office_desk_2_storage office_shelf_3) (= (distance  office_desk_2_storage office_shelf_3) 28)
(connected office_desk_2_storage office_desk_5) (= (distance  office_desk_2_storage office_desk_5) 32)
(connected office_desk_3_storage office_desk_2_storage) (= (distance  office_desk_3_storage office_desk_2_storage) 6)
(connected office_desk_3_storage office_corridor) (= (distance  office_desk_3_storage office_corridor) 8)
(connected office_desk_3_storage office_desk_2) (= (distance  office_desk_3_storage office_desk_2) 11)
(connected office_desk_3_storage office_shelf_2) (= (distance  office_desk_3_storage office_shelf_2) 13)
(connected office_desk_3_storage office_shelf_1) (= (distance  office_desk_3_storage office_shelf_1) 22)
(connected office_desk_3_storage office_storage_1) (= (distance  office_desk_3_storage office_storage_1) 28)
(connected office_desk_3_storage office_desk_1_cabinet) (= (distance  office_desk_3_storage office_desk_1_cabinet) 34)
(connected office_entrance_2 office_door_2) (= (distance  office_entrance_2 office_door_2) 5)
(connected office_entrance_2 office_desk_3) (= (distance  office_entrance_2 office_desk_3) 5)
(connected office_entrance_2 kitchen_door_2) (= (distance  office_entrance_2 kitchen_door_2) 8)
(connected office_entrance_2 office_storage_2) (= (distance  office_entrance_2 office_storage_2) 12)
(connected office_entrance_2 office_shelf_3) (= (distance  office_entrance_2 office_shelf_3) 13)
(connected office_entrance_2 office_desk_5) (= (distance  office_entrance_2 office_desk_5) 13)
(connected office_entrance_2 office_desk_5_storage) (= (distance  office_entrance_2 office_desk_5_storage) 15)
(connected office_entrance_2 corridor) (= (distance  office_entrance_2 corridor) 15)
(connected office_entrance_2 office_shelf_2) (= (distance  office_entrance_2 office_shelf_2) 15)
(connected office_entrance_2 corridor_shelf_2) (= (distance  office_entrance_2 corridor_shelf_2) 17)
(connected office_entrance_2 main_office_door) (= (distance  office_entrance_2 main_office_door) 24)
(connected office_entrance_2 main_office_doorway) (= (distance  office_entrance_2 main_office_doorway) 29)
(connected office_entrance_2 main_office_entrance) (= (distance  office_entrance_2 main_office_entrance) 31)
(connected office_entrance_2 main_office_corridor) (= (distance  office_entrance_2 main_office_corridor) 36)
(connected office_door_2 office_entrance_2) (= (distance  office_door_2 office_entrance_2) 5)
(connected office_door_2 kitchen_door_2) (= (distance  office_door_2 kitchen_door_2) 7)
(connected office_door_2 office_desk_3) (= (distance  office_door_2 office_desk_3) 9)
(connected office_door_2 office_desk_5) (= (distance  office_door_2 office_desk_5) 10)
(connected office_door_2 office_desk_5_storage) (= (distance  office_door_2 office_desk_5_storage) 10)
(connected office_door_2 office_shelf_3) (= (distance  office_door_2 office_shelf_3) 11)
(connected office_door_2 office_storage_2) (= (distance  office_door_2 office_storage_2) 13)
(connected office_door_2 corridor) (= (distance  office_door_2 corridor) 14)
(connected office_door_2 corridor_shelf_2) (= (distance  office_door_2 corridor_shelf_2) 14)
(connected office_door_2 meeting_room_hallway) (= (distance  office_door_2 meeting_room_hallway) 17)
(connected office_door_2 office_shelf_2) (= (distance  office_door_2 office_shelf_2) 19)
(connected office_door_2 office_corridor) (= (distance  office_door_2 office_corridor) 21)
(connected office_door_2 main_office_door) (= (distance  office_door_2 main_office_door) 22)
(connected office_door_2 meeting_room_door) (= (distance  office_door_2 meeting_room_door) 23)
(connected office_door_2 main_office_doorway) (= (distance  office_door_2 main_office_doorway) 27)
(connected office_door_2 main_office_entrance) (= (distance  office_door_2 main_office_entrance) 30)
(connected office_door_2 meeting_room) (= (distance  office_door_2 meeting_room) 31)
(connected office_door_2 main_office_corridor) (= (distance  office_door_2 main_office_corridor) 34)
(connected office_door_2 main_office_cupboard) (= (distance  office_door_2 main_office_cupboard) 36)
(connected office_door_2 kitchen_chair) (= (distance  office_door_2 kitchen_chair) 39)
(connected office_desk_1_storage office_desk_1) (= (distance  office_desk_1_storage office_desk_1) 7)
(connected office_desk_1_storage office_door_1) (= (distance  office_desk_1_storage office_door_1) 8)
(connected office_desk_1_storage kitchen_door_1) (= (distance  office_desk_1_storage kitchen_door_1) 11)
(connected office_desk_1_storage office_entrance_1) (= (distance  office_desk_1_storage office_entrance_1) 13)
(connected office_desk_1_storage office_storage_1) (= (distance  office_desk_1_storage office_storage_1) 15)
(connected office_desk_1_storage office_desk_2_cabinet) (= (distance  office_desk_1_storage office_desk_2_cabinet) 17)
(connected office_desk_1_storage office_shelf_1) (= (distance  office_desk_1_storage office_shelf_1) 19)
(connected office_desk_1_storage kitchen_table_3) (= (distance  office_desk_1_storage kitchen_table_3) 21)
(connected office_desk_1_storage office_desk_2) (= (distance  office_desk_1_storage office_desk_2) 25)
(connected office_desk_1_storage office_desk_4_storage) (= (distance  office_desk_1_storage office_desk_4_storage) 26)
(connected office_desk_1_storage kitchen_table_4) (= (distance  office_desk_1_storage kitchen_table_4) 32)
(connected office_desk_1_storage office_corridor) (= (distance  office_desk_1_storage office_corridor) 35)
(connected office_desk_1_storage office_shelf_2) (= (distance  office_desk_1_storage office_shelf_2) 41)
(connected office_desk_1_storage kitchen_chair) (= (distance  office_desk_1_storage kitchen_chair) 42)
(connected office_desk_1_storage office_desk_3) (= (distance  office_desk_1_storage office_desk_3) 47)
(connected office_desk_1_storage meeting_room_door) (= (distance  office_desk_1_storage meeting_room_door) 51)
(connected office_desk_1_storage office_storage_2) (= (distance  office_desk_1_storage office_storage_2) 51)
(connected office_desk_1_storage office_shelf_3) (= (distance  office_desk_1_storage office_shelf_3) 55)
(connected office_desk_1_storage office_desk_5) (= (distance  office_desk_1_storage office_desk_5) 59)
(connected office_desk_5_storage office_door_2) (= (distance  office_desk_5_storage office_door_2) 10)
(connected office_desk_5_storage office_shelf_3) (= (distance  office_desk_5_storage office_shelf_3) 13)
(connected office_desk_5_storage office_entrance_2) (= (distance  office_desk_5_storage office_entrance_2) 15)
(connected office_desk_5_storage office_storage_2) (= (distance  office_desk_5_storage office_storage_2) 17)
(connected office_desk_5_storage office_desk_3) (= (distance  office_desk_5_storage office_desk_3) 18)
(connected office_desk_5_storage meeting_room_hallway) (= (distance  office_desk_5_storage meeting_room_hallway) 25)
(connected office_desk_5_storage office_shelf_2) (= (distance  office_desk_5_storage office_shelf_2) 26)
(connected office_desk_5_storage office_corridor) (= (distance  office_desk_5_storage office_corridor) 30)
(connected office_desk_5_storage corridor_centre) (= (distance  office_desk_5_storage corridor_centre) 33)
(connected office_desk_5_storage office_desk_2) (= (distance  office_desk_5_storage office_desk_2) 40)
(connected office_desk_5_storage kitchen_corridor_2) (= (distance  office_desk_5_storage kitchen_corridor_2) 42)
(connected office_desk_5_storage office_desk_2_cabinet) (= (distance  office_desk_5_storage office_desk_2_cabinet) 48)
(connected office_desk_5_storage office_shelf_1) (= (distance  office_desk_5_storage office_shelf_1) 49)
(connected office_desk_5_storage office_storage_1) (= (distance  office_desk_5_storage office_storage_1) 56)
(connected office_desk_5_storage office_desk_1) (= (distance  office_desk_5_storage office_desk_1) 60)
(connected office_desk_5_storage office_desk_1_cabinet) (= (distance  office_desk_5_storage office_desk_1_cabinet) 62)
(connected office_desk_2_cabinet office_entrance_1) (= (distance  office_desk_2_cabinet office_entrance_1) 6)
(connected office_desk_2_cabinet office_desk_2) (= (distance  office_desk_2_cabinet office_desk_2) 8)
(connected office_desk_2_cabinet office_shelf_1) (= (distance  office_desk_2_cabinet office_shelf_1) 8)
(connected office_desk_2_cabinet office_door_1) (= (distance  office_desk_2_cabinet office_door_1) 10)
(connected office_desk_2_cabinet office_desk_4_storage) (= (distance  office_desk_2_cabinet office_desk_4_storage) 11)
(connected office_desk_2_cabinet office_storage_1) (= (distance  office_desk_2_cabinet office_storage_1) 12)
(connected office_desk_2_cabinet office_desk_1) (= (distance  office_desk_2_cabinet office_desk_1) 13)
(connected office_desk_2_cabinet kitchen_door_1) (= (distance  office_desk_2_cabinet kitchen_door_1) 14)
(connected office_desk_2_cabinet office_desk_1_cabinet) (= (distance  office_desk_2_cabinet office_desk_1_cabinet) 16)
(connected office_desk_2_cabinet office_desk_1_storage) (= (distance  office_desk_2_cabinet office_desk_1_storage) 17)
(connected office_desk_2_cabinet office_corridor) (= (distance  office_desk_2_cabinet office_corridor) 19)
(connected office_desk_2_cabinet fridge) (= (distance  office_desk_2_cabinet fridge) 21)
(connected office_desk_2_cabinet office_shelf_2) (= (distance  office_desk_2_cabinet office_shelf_2) 24)
(connected office_desk_2_cabinet coffee_table_3) (= (distance  office_desk_2_cabinet coffee_table_3) 30)
(connected office_desk_2_cabinet office_desk_3) (= (distance  office_desk_2_cabinet office_desk_3) 30)
(connected office_desk_2_cabinet office_storage_2) (= (distance  office_desk_2_cabinet office_storage_2) 34)
(connected office_desk_2_cabinet office_shelf_3) (= (distance  office_desk_2_cabinet office_shelf_3) 38)
(connected office_desk_2_cabinet office_desk_5) (= (distance  office_desk_2_cabinet office_desk_5) 43)
(connected office_desk_2_cabinet office_desk_5_storage) (= (distance  office_desk_2_cabinet office_desk_5_storage) 48)
(connected office_desk_3 office_entrance_2) (= (distance  office_desk_3 office_entrance_2) 5)
(connected office_desk_3 office_storage_2) (= (distance  office_desk_3 office_storage_2) 8)
(connected office_desk_3 office_door_2) (= (distance  office_desk_3 office_door_2) 9)
(connected office_desk_3 office_shelf_2) (= (distance  office_desk_3 office_shelf_2) 10)
(connected office_desk_3 office_shelf_3) (= (distance  office_desk_3 office_shelf_3) 10)
(connected office_desk_3 office_corridor) (= (distance  office_desk_3 office_corridor) 12)
(connected office_desk_3 office_desk_5) (= (distance  office_desk_3 office_desk_5) 13)
(connected office_desk_3 kitchen_door_2) (= (distance  office_desk_3 kitchen_door_2) 14)
(connected office_desk_3 office_desk_5_storage) (= (distance  office_desk_3 office_desk_5_storage) 18)
(connected office_desk_3 office_desk_2) (= (distance  office_desk_3 office_desk_2) 22)
(connected office_desk_3 corridor_shelf_2) (= (distance  office_desk_3 corridor_shelf_2) 23)
(connected office_desk_3 main_office_door) (= (distance  office_desk_3 main_office_door) 30)
(connected office_desk_3 office_desk_2_cabinet) (= (distance  office_desk_3 office_desk_2_cabinet) 30)
(connected office_desk_3 office_shelf_1) (= (distance  office_desk_3 office_shelf_1) 32)
(connected office_desk_3 office_storage_1) (= (distance  office_desk_3 office_storage_1) 38)
(connected office_desk_3 office_desk_1) (= (distance  office_desk_3 office_desk_1) 43)
(connected office_desk_3 office_desk_1_cabinet) (= (distance  office_desk_3 office_desk_1_cabinet) 44)
(connected office_desk_3 office_desk_1_storage) (= (distance  office_desk_3 office_desk_1_storage) 47)
(connected office_desk_2 office_desk_2_storage) (= (distance  office_desk_2 office_desk_2_storage) 6)
(connected office_desk_2 office_desk_2_cabinet) (= (distance  office_desk_2 office_desk_2_cabinet) 8)
(connected office_desk_2 office_desk_4_storage) (= (distance  office_desk_2 office_desk_4_storage) 10)
(connected office_desk_2 office_corridor) (= (distance  office_desk_2 office_corridor) 11)
(connected office_desk_2 office_desk_3_storage) (= (distance  office_desk_2 office_desk_3_storage) 11)
(connected office_desk_2 office_shelf_1) (= (distance  office_desk_2 office_shelf_1) 12)
(connected office_desk_2 office_shelf_2) (= (distance  office_desk_2 office_shelf_2) 16)
(connected office_desk_2 office_storage_1) (= (distance  office_desk_2 office_storage_1) 17)
(connected office_desk_2 office_desk_1) (= (distance  office_desk_2 office_desk_1) 21)
(connected office_desk_2 office_desk_3) (= (distance  office_desk_2 office_desk_3) 22)
(connected office_desk_2 office_desk_1_cabinet) (= (distance  office_desk_2 office_desk_1_cabinet) 23)
(connected office_desk_2 office_desk_1_storage) (= (distance  office_desk_2 office_desk_1_storage) 25)
(connected office_desk_2 office_storage_2) (= (distance  office_desk_2 office_storage_2) 27)
(connected office_desk_2 office_shelf_3) (= (distance  office_desk_2 office_shelf_3) 31)
(connected office_desk_2 office_desk_5) (= (distance  office_desk_2 office_desk_5) 35)
(connected office_desk_2 office_desk_5_storage) (= (distance  office_desk_2 office_desk_5_storage) 40)
(connected office_desk_1 office_desk_1_storage) (= (distance  office_desk_1 office_desk_1_storage) 7)
(connected office_desk_1 office_desk_1_cabinet) (= (distance  office_desk_1 office_desk_1_cabinet) 7)
(connected office_desk_1 office_storage_1) (= (distance  office_desk_1 office_storage_1) 8)
(connected office_desk_1 office_door_1) (= (distance  office_desk_1 office_door_1) 9)
(connected office_desk_1 office_entrance_1) (= (distance  office_desk_1 office_entrance_1) 12)
(connected office_desk_1 office_desk_2_cabinet) (= (distance  office_desk_1 office_desk_2_cabinet) 13)
(connected office_desk_1 office_shelf_1) (= (distance  office_desk_1 office_shelf_1) 13)
(connected office_desk_1 kitchen_door_1) (= (distance  office_desk_1 kitchen_door_1) 14)
(connected office_desk_1 office_desk_4_storage) (= (distance  office_desk_1 office_desk_4_storage) 20)
(connected office_desk_1 office_desk_2) (= (distance  office_desk_1 office_desk_2) 21)
(connected office_desk_1 kitchen_table_2) (= (distance  office_desk_1 kitchen_table_2) 25)
(connected office_desk_1 coffee_table_4) (= (distance  office_desk_1 coffee_table_4) 28)
(connected office_desk_1 kitchen_hallway) (= (distance  office_desk_1 kitchen_hallway) 31)
(connected office_desk_1 office_corridor) (= (distance  office_desk_1 office_corridor) 31)
(connected office_desk_1 office_shelf_2) (= (distance  office_desk_1 office_shelf_2) 36)
(connected office_desk_1 kitchen_corridor) (= (distance  office_desk_1 kitchen_corridor) 40)
(connected office_desk_1 office_desk_3) (= (distance  office_desk_1 office_desk_3) 43)
(connected office_desk_1 office_storage_2) (= (distance  office_desk_1 office_storage_2) 46)
(connected office_desk_1 kitchen_counter) (= (distance  office_desk_1 kitchen_counter) 50)
(connected office_desk_1 office_shelf_3) (= (distance  office_desk_1 office_shelf_3) 51)
(connected office_corridor office_shelf_2) (= (distance  office_corridor office_shelf_2) 6)
(connected office_corridor office_desk_3_storage) (= (distance  office_corridor office_desk_3_storage) 8)
(connected office_corridor office_desk_2_storage) (= (distance  office_corridor office_desk_2_storage) 10)
(connected office_corridor office_desk_2) (= (distance  office_corridor office_desk_2) 11)
(connected office_corridor office_desk_3) (= (distance  office_corridor office_desk_3) 12)
(connected office_corridor office_storage_2) (= (distance  office_corridor office_storage_2) 16)
(connected office_corridor office_desk_2_cabinet) (= (distance  office_corridor office_desk_2_cabinet) 19)
(connected office_corridor office_shelf_1) (= (distance  office_corridor office_shelf_1) 20)
(connected office_corridor office_shelf_3) (= (distance  office_corridor office_shelf_3) 20)
(connected office_corridor office_door_2) (= (distance  office_corridor office_door_2) 21)
(connected office_corridor office_desk_5) (= (distance  office_corridor office_desk_5) 24)
(connected office_corridor office_storage_1) (= (distance  office_corridor office_storage_1) 26)
(connected office_corridor office_desk_5_storage) (= (distance  office_corridor office_desk_5_storage) 30)
(connected office_corridor office_desk_1) (= (distance  office_corridor office_desk_1) 31)
(connected office_corridor office_desk_1_cabinet) (= (distance  office_corridor office_desk_1_cabinet) 32)
(connected office_corridor office_desk_1_storage) (= (distance  office_corridor office_desk_1_storage) 35)
(connected office_desk_5 office_shelf_3) (= (distance  office_desk_5 office_shelf_3) 5)
(connected office_desk_5 office_door_2) (= (distance  office_desk_5 office_door_2) 10)
(connected office_desk_5 office_storage_2) (= (distance  office_desk_5 office_storage_2) 10)
(connected office_desk_5 office_entrance_2) (= (distance  office_desk_5 office_entrance_2) 13)
(connected office_desk_5 office_desk_3) (= (distance  office_desk_5 office_desk_3) 13)
(connected office_desk_5 kitchen_door_2) (= (distance  office_desk_5 kitchen_door_2) 16)
(connected office_desk_5 office_shelf_2) (= (distance  office_desk_5 office_shelf_2) 20)
(connected office_desk_5 corridor) (= (distance  office_desk_5 corridor) 23)
(connected office_desk_5 office_corridor) (= (distance  office_desk_5 office_corridor) 24)
(connected office_desk_5 meeting_room_hallway) (= (distance  office_desk_5 meeting_room_hallway) 26)
(connected office_desk_5 office_desk_2_storage) (= (distance  office_desk_5 office_desk_2_storage) 32)
(connected office_desk_5 meeting_room_door) (= (distance  office_desk_5 meeting_room_door) 33)
(connected office_desk_5 office_desk_2) (= (distance  office_desk_5 office_desk_2) 35)
(connected office_desk_5 meeting_room) (= (distance  office_desk_5 meeting_room) 40)
(connected office_desk_5 office_desk_2_cabinet) (= (distance  office_desk_5 office_desk_2_cabinet) 43)
(connected office_desk_5 office_desk_1) (= (distance  office_desk_5 office_desk_1) 55)
(connected office_desk_5 office_desk_1_storage) (= (distance  office_desk_5 office_desk_1_storage) 59)
(connected office_shelf_2 office_corridor) (= (distance  office_shelf_2 office_corridor) 6)
(connected office_shelf_2 office_desk_3) (= (distance  office_shelf_2 office_desk_3) 10)
(connected office_shelf_2 office_storage_2) (= (distance  office_shelf_2 office_storage_2) 10)
(connected office_shelf_2 office_desk_3_storage) (= (distance  office_shelf_2 office_desk_3_storage) 13)
(connected office_shelf_2 office_shelf_3) (= (distance  office_shelf_2 office_shelf_3) 15)
(connected office_shelf_2 office_entrance_2) (= (distance  office_shelf_2 office_entrance_2) 15)
(connected office_shelf_2 office_desk_2_storage) (= (distance  office_shelf_2 office_desk_2_storage) 16)
(connected office_shelf_2 office_desk_2) (= (distance  office_shelf_2 office_desk_2) 16)
(connected office_shelf_2 office_door_2) (= (distance  office_shelf_2 office_door_2) 19)
(connected office_shelf_2 office_desk_5) (= (distance  office_shelf_2 office_desk_5) 20)
(connected office_shelf_2 kitchen_door_2) (= (distance  office_shelf_2 kitchen_door_2) 24)
(connected office_shelf_2 office_desk_2_cabinet) (= (distance  office_shelf_2 office_desk_2_cabinet) 24)
(connected office_shelf_2 office_desk_5_storage) (= (distance  office_shelf_2 office_desk_5_storage) 26)
(connected office_shelf_2 corridor_shelf_2) (= (distance  office_shelf_2 corridor_shelf_2) 32)
(connected office_shelf_2 office_door_1) (= (distance  office_shelf_2 office_door_1) 34)
(connected office_shelf_2 office_desk_1) (= (distance  office_shelf_2 office_desk_1) 36)
(connected office_shelf_2 office_desk_1_storage) (= (distance  office_shelf_2 office_desk_1_storage) 41)
(connected office_shelf_3 office_storage_2) (= (distance  office_shelf_3 office_storage_2) 4)
(connected office_shelf_3 office_desk_5) (= (distance  office_shelf_3 office_desk_5) 5)
(connected office_shelf_3 office_desk_3) (= (distance  office_shelf_3 office_desk_3) 10)
(connected office_shelf_3 office_door_2) (= (distance  office_shelf_3 office_door_2) 11)
(connected office_shelf_3 office_entrance_2) (= (distance  office_shelf_3 office_entrance_2) 13)
(connected office_shelf_3 office_desk_5_storage) (= (distance  office_shelf_3 office_desk_5_storage) 13)
(connected office_shelf_3 office_shelf_2) (= (distance  office_shelf_3 office_shelf_2) 15)
(connected office_shelf_3 kitchen_door_2) (= (distance  office_shelf_3 kitchen_door_2) 18)
(connected office_shelf_3 office_corridor) (= (distance  office_shelf_3 office_corridor) 20)
(connected office_shelf_3 corridor) (= (distance  office_shelf_3 corridor) 25)
(connected office_shelf_3 office_desk_2_storage) (= (distance  office_shelf_3 office_desk_2_storage) 28)
(connected office_shelf_3 office_desk_2) (= (distance  office_shelf_3 office_desk_2) 31)
(connected office_shelf_3 main_office_door) (= (distance  office_shelf_3 main_office_door) 33)
(connected office_shelf_3 main_office_doorway) (= (distance  office_shelf_3 main_office_doorway) 38)
(connected office_shelf_3 office_desk_2_cabinet) (= (distance  office_shelf_3 office_desk_2_cabinet) 38)
(connected office_shelf_3 main_office_entrance) (= (distance  office_shelf_3 main_office_entrance) 40)
(connected office_shelf_3 meeting_room) (= (distance  office_shelf_3 meeting_room) 41)
(connected office_shelf_3 main_office_corridor) (= (distance  office_shelf_3 main_office_corridor) 45)
(connected office_shelf_3 main_office_cupboard) (= (distance  office_shelf_3 main_office_cupboard) 47)
(connected office_shelf_3 office_desk_1) (= (distance  office_shelf_3 office_desk_1) 51)
(connected office_storage_2 office_shelf_3) (= (distance  office_storage_2 office_shelf_3) 4)
(connected office_storage_2 office_desk_3) (= (distance  office_storage_2 office_desk_3) 8)
(connected office_storage_2 office_desk_5) (= (distance  office_storage_2 office_desk_5) 10)
(connected office_storage_2 office_shelf_2) (= (distance  office_storage_2 office_shelf_2) 10)
(connected office_storage_2 office_entrance_2) (= (distance  office_storage_2 office_entrance_2) 12)
(connected office_storage_2 office_door_2) (= (distance  office_storage_2 office_door_2) 13)
(connected office_storage_2 office_corridor) (= (distance  office_storage_2 office_corridor) 16)
(connected office_storage_2 office_desk_5_storage) (= (distance  office_storage_2 office_desk_5_storage) 17)
(connected office_storage_2 kitchen_door_2) (= (distance  office_storage_2 kitchen_door_2) 19)
(connected office_storage_2 office_desk_2_storage) (= (distance  office_storage_2 office_desk_2_storage) 25)
(connected office_storage_2 corridor) (= (distance  office_storage_2 corridor) 26)
(connected office_storage_2 office_desk_2) (= (distance  office_storage_2 office_desk_2) 27)
(connected office_storage_2 office_desk_2_cabinet) (= (distance  office_storage_2 office_desk_2_cabinet) 34)
(connected office_storage_2 main_office_door) (= (distance  office_storage_2 main_office_door) 35)
(connected office_storage_2 main_office_doorway) (= (distance  office_storage_2 main_office_doorway) 40)
(connected office_storage_2 main_office_entrance) (= (distance  office_storage_2 main_office_entrance) 42)
(connected office_storage_2 office_desk_1) (= (distance  office_storage_2 office_desk_1) 46)
(connected office_storage_2 main_office_corridor) (= (distance  office_storage_2 main_office_corridor) 47)
(connected office_storage_2 main_office_cupboard) (= (distance  office_storage_2 main_office_cupboard) 48)
(connected office_storage_2 office_desk_1_storage) (= (distance  office_storage_2 office_desk_1_storage) 51)
(connected office_shelf_1 office_storage_1) (= (distance  office_shelf_1 office_storage_1) 7)
(connected office_shelf_1 office_desk_4_storage) (= (distance  office_shelf_1 office_desk_4_storage) 7)
(connected office_shelf_1 office_desk_2_cabinet) (= (distance  office_shelf_1 office_desk_2_cabinet) 8)
(connected office_shelf_1 office_desk_2) (= (distance  office_shelf_1 office_desk_2) 12)
(connected office_shelf_1 office_desk_1_cabinet) (= (distance  office_shelf_1 office_desk_1_cabinet) 12)
(connected office_shelf_1 office_desk_1) (= (distance  office_shelf_1 office_desk_1) 13)
(connected office_shelf_1 office_entrance_1) (= (distance  office_shelf_1 office_entrance_1) 13)
(connected office_shelf_1 office_door_1) (= (distance  office_shelf_1 office_door_1) 16)
(connected office_shelf_1 office_desk_1_storage) (= (distance  office_shelf_1 office_desk_1_storage) 19)
(connected office_shelf_1 office_corridor) (= (distance  office_shelf_1 office_corridor) 20)
(connected office_shelf_1 kitchen_door_1) (= (distance  office_shelf_1 kitchen_door_1) 20)
(connected office_shelf_1 office_desk_3_storage) (= (distance  office_shelf_1 office_desk_3_storage) 22)
(connected office_shelf_1 fridge) (= (distance  office_shelf_1 fridge) 28)
(connected office_shelf_1 office_desk_3) (= (distance  office_shelf_1 office_desk_3) 32)
(connected office_shelf_1 coffee_table_4) (= (distance  office_shelf_1 coffee_table_4) 35)
(connected office_shelf_1 coffee_table_3) (= (distance  office_shelf_1 coffee_table_3) 37)
(connected office_shelf_1 office_door_2) (= (distance  office_shelf_1 office_door_2) 41)
(connected office_shelf_1 office_desk_5_storage) (= (distance  office_shelf_1 office_desk_5_storage) 49)
(connected office_storage_1 office_desk_1_cabinet) (= (distance  office_storage_1 office_desk_1_cabinet) 6)
(connected office_storage_1 office_shelf_1) (= (distance  office_storage_1 office_shelf_1) 7)
(connected office_storage_1 office_desk_1) (= (distance  office_storage_1 office_desk_1) 8)
(connected office_storage_1 office_desk_2_cabinet) (= (distance  office_storage_1 office_desk_2_cabinet) 12)
(connected office_storage_1 office_entrance_1) (= (distance  office_storage_1 office_entrance_1) 14)
(connected office_storage_1 office_door_1) (= (distance  office_storage_1 office_door_1) 15)
(connected office_storage_1 office_desk_1_storage) (= (distance  office_storage_1 office_desk_1_storage) 15)
(connected office_storage_1 office_desk_2) (= (distance  office_storage_1 office_desk_2) 17)
(connected office_storage_1 kitchen_door_1) (= (distance  office_storage_1 kitchen_door_1) 20)
(connected office_storage_1 office_corridor) (= (distance  office_storage_1 office_corridor) 26)
(connected office_storage_1 fridge) (= (distance  office_storage_1 fridge) 27)
(connected office_storage_1 office_desk_3_storage) (= (distance  office_storage_1 office_desk_3_storage) 28)
(connected office_storage_1 kitchen_table_2) (= (distance  office_storage_1 kitchen_table_2) 29)
(connected office_storage_1 coffee_table_4) (= (distance  office_storage_1 coffee_table_4) 34)
(connected office_storage_1 kitchen_hallway) (= (distance  office_storage_1 kitchen_hallway) 36)
(connected office_storage_1 office_desk_3) (= (distance  office_storage_1 office_desk_3) 38)
(connected office_storage_1 kitchen_corridor) (= (distance  office_storage_1 kitchen_corridor) 45)
(connected office_storage_1 office_door_2) (= (distance  office_storage_1 office_door_2) 47)
(connected office_storage_1 kitchen_counter) (= (distance  office_storage_1 kitchen_counter) 55)
(connected office_storage_1 office_desk_5_storage) (= (distance  office_storage_1 office_desk_5_storage) 56)
(connected office_desk_4_storage office_shelf_1) (= (distance  office_desk_4_storage office_shelf_1) 7)
(connected office_desk_4_storage office_desk_2) (= (distance  office_desk_4_storage office_desk_2) 10)
(connected office_desk_4_storage office_desk_2_cabinet) (= (distance  office_desk_4_storage office_desk_2_cabinet) 11)
(connected office_desk_4_storage office_desk_2_storage) (= (distance  office_desk_4_storage office_desk_2_storage) 16)
(connected office_desk_4_storage office_entrance_1) (= (distance  office_desk_4_storage office_entrance_1) 17)
(connected office_desk_4_storage office_desk_1) (= (distance  office_desk_4_storage office_desk_1) 20)
(connected office_desk_4_storage office_door_1) (= (distance  office_desk_4_storage office_door_1) 21)
(connected office_desk_4_storage kitchen_door_1) (= (distance  office_desk_4_storage kitchen_door_1) 25)
(connected office_desk_4_storage office_desk_1_storage) (= (distance  office_desk_4_storage office_desk_1_storage) 26)
(connected office_desk_4_storage fridge) (= (distance  office_desk_4_storage fridge) 33)
(connected office_desk_4_storage coffee_table_3) (= (distance  office_desk_4_storage coffee_table_3) 41)
(connected office_desk_1_cabinet office_storage_1) (= (distance  office_desk_1_cabinet office_storage_1) 6)
(connected office_desk_1_cabinet office_desk_1) (= (distance  office_desk_1_cabinet office_desk_1) 7)
(connected office_desk_1_cabinet office_shelf_1) (= (distance  office_desk_1_cabinet office_shelf_1) 12)
(connected office_desk_1_cabinet office_door_1) (= (distance  office_desk_1_cabinet office_door_1) 16)
(connected office_desk_1_cabinet office_desk_2_cabinet) (= (distance  office_desk_1_cabinet office_desk_2_cabinet) 16)
(connected office_desk_1_cabinet office_entrance_1) (= (distance  office_desk_1_cabinet office_entrance_1) 17)
(connected office_desk_1_cabinet kitchen_door_1) (= (distance  office_desk_1_cabinet kitchen_door_1) 21)
(connected office_desk_1_cabinet office_desk_2) (= (distance  office_desk_1_cabinet office_desk_2) 23)
(connected office_desk_1_cabinet kitchen_table_2) (= (distance  office_desk_1_cabinet kitchen_table_2) 32)
(connected office_desk_1_cabinet office_corridor) (= (distance  office_desk_1_cabinet office_corridor) 32)
(connected office_desk_1_cabinet office_desk_3_storage) (= (distance  office_desk_1_cabinet office_desk_3_storage) 34)
(connected office_desk_1_cabinet coffee_table_4) (= (distance  office_desk_1_cabinet coffee_table_4) 35)
(connected office_desk_1_cabinet kitchen_hallway) (= (distance  office_desk_1_cabinet kitchen_hallway) 38)
(connected office_desk_1_cabinet office_desk_3) (= (distance  office_desk_1_cabinet office_desk_3) 44)
(connected office_desk_1_cabinet kitchen_corridor) (= (distance  office_desk_1_cabinet kitchen_corridor) 47)
(connected office_desk_1_cabinet office_door_2) (= (distance  office_desk_1_cabinet office_door_2) 53)
(connected office_desk_1_cabinet kitchen_counter) (= (distance  office_desk_1_cabinet kitchen_counter) 57)
(connected office_desk_1_cabinet office_desk_5_storage) (= (distance  office_desk_1_cabinet office_desk_5_storage) 62)

)
(:goal (and
    (robot_at robot_assistant kitchen_shelf)
    (object_at paper kitchen_counter)
    (object_at mug entrance)
    (object_at post1 main_office_desk) 
    (person_found person1)
    (person_asked person2)
    (object_at post2 person2)
))
)
